[package]
name = "obsqra_contracts"
version = "0.1.0"
edition = "2021_11"

[dependencies]
starknet = ">=2.0.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.20.0" }

[[lib]]
path = "src/lib.cairo"

